/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramaCRUD;

import ConexionCRUD.Conexion;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class InterfazUsuarios extends javax.swing.JInternalFrame {
DefaultTableModel modelo;

    /**
     * Creates new form InterfazUsuarios
     */
    public InterfazUsuarios() {
        initComponents();
        BloquearControles();
        CargarCBTipoUsuarios();
        CargarTablaUsuarios("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneNuevoUsuario = new javax.swing.JTabbedPane();
        jPanelCrear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfCedula = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfContrasena = new javax.swing.JTextField();
        jcbTipoUsuario = new javax.swing.JComboBox<>();
        jbCrearUsuario = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jPanelModificar = new javax.swing.JPanel();
        jcbTipoUsuarioMod = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfContrasenaMod = new javax.swing.JTextField();
        jtfApellidoMod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfNombreMod = new javax.swing.JTextField();
        jtfCedulaMod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbActualizarUsuarioMod = new javax.swing.JButton();
        jbCerrarMod = new javax.swing.JButton();
        jbEliminarUsuarioMod = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbBuscarUsuarioMod = new javax.swing.JButton();
        jbCancelarUsuarioMod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Usuarios = new javax.swing.JTable();

        setForeground(java.awt.Color.white);

        jTabbedPaneNuevoUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese La Cédula:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese El Nombre:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese El Apellido:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese La Contraseña:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Seleccione El Tipo De Usuario: ");

        jtfCedula.setPreferredSize(new java.awt.Dimension(150, 25));
        jtfCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCedulaActionPerformed(evt);
            }
        });
        jtfCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCedulaKeyTyped(evt);
            }
        });

        jtfNombre.setPreferredSize(new java.awt.Dimension(150, 25));
        jtfNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNombreMouseClicked(evt);
            }
        });
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        jtfApellido.setPreferredSize(new java.awt.Dimension(150, 25));

        jtfContrasena.setPreferredSize(new java.awt.Dimension(150, 25));

        jcbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTipoUsuario.setPreferredSize(new java.awt.Dimension(150, 25));

        jbCrearUsuario.setText("CREAR USUARIO");
        jbCrearUsuario.setPreferredSize(new java.awt.Dimension(150, 50));
        jbCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearUsuarioActionPerformed(evt);
            }
        });

        jbCerrar.setText("CERRAR");
        jbCerrar.setToolTipText("");
        jbCerrar.setPreferredSize(new java.awt.Dimension(150, 50));
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearLayout = new javax.swing.GroupLayout(jPanelCrear);
        jPanelCrear.setLayout(jPanelCrearLayout);
        jPanelCrearLayout.setHorizontalGroup(
            jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearLayout.createSequentialGroup()
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(42, 42, 42))
                                .addGroup(jPanelCrearLayout.createSequentialGroup()
                                    .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanelCrearLayout.createSequentialGroup()
                                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearLayout.createSequentialGroup()
                        .addContainerGap(473, Short.MAX_VALUE)
                        .addComponent(jbCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelCrearLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jbCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCrearLayout.setVerticalGroup(
            jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jbCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jbCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneNuevoUsuario.addTab("Crear Nuevo Usuario", jPanelCrear);

        jcbTipoUsuarioMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTipoUsuarioMod.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tipo De Usuario");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Contraseña Del Usuario");

        jtfContrasenaMod.setPreferredSize(new java.awt.Dimension(150, 25));

        jtfApellidoMod.setPreferredSize(new java.awt.Dimension(150, 25));
        jtfApellidoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfApellidoModKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Apellido Del Usuario");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Nombre Del Usuario");

        jtfNombreMod.setPreferredSize(new java.awt.Dimension(150, 25));
        jtfNombreMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreModKeyTyped(evt);
            }
        });

        jtfCedulaMod.setPreferredSize(new java.awt.Dimension(150, 25));
        jtfCedulaMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCedulaModActionPerformed(evt);
            }
        });
        jtfCedulaMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCedulaModKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Ingrese La Cédula:");

        jbActualizarUsuarioMod.setText("ACTUALIZAR USUARIO");
        jbActualizarUsuarioMod.setPreferredSize(new java.awt.Dimension(150, 50));
        jbActualizarUsuarioMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarUsuarioModActionPerformed(evt);
            }
        });

        jbCerrarMod.setText("CERRAR");
        jbCerrarMod.setToolTipText("");
        jbCerrarMod.setPreferredSize(new java.awt.Dimension(150, 50));
        jbCerrarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarModActionPerformed(evt);
            }
        });

        jbEliminarUsuarioMod.setText("ELIMINAR USUARIO");
        jbEliminarUsuarioMod.setPreferredSize(new java.awt.Dimension(150, 50));
        jbEliminarUsuarioMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarUsuarioModActionPerformed(evt);
            }
        });

        jbBuscarUsuarioMod.setText("BUSCAR USUARIO");
        jbBuscarUsuarioMod.setPreferredSize(new java.awt.Dimension(150, 50));
        jbBuscarUsuarioMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarUsuarioModActionPerformed(evt);
            }
        });

        jbCancelarUsuarioMod.setText("CANCELAR");
        jbCancelarUsuarioMod.setPreferredSize(new java.awt.Dimension(150, 50));
        jbCancelarUsuarioMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarUsuarioModActionPerformed(evt);
            }
        });

        jTable_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(jTable_Usuarios);

        javax.swing.GroupLayout jPanelModificarLayout = new javax.swing.GroupLayout(jPanelModificar);
        jPanelModificar.setLayout(jPanelModificarLayout);
        jPanelModificarLayout.setHorizontalGroup(
            jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificarLayout.createSequentialGroup()
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModificarLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbTipoUsuarioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfContrasenaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfApellidoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanelModificarLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)
                                .addGap(77, 77, 77)
                                .addComponent(jtfCedulaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarLayout.createSequentialGroup()
                                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbActualizarUsuarioMod, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jbEliminarUsuarioMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbCancelarUsuarioMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbCerrarMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarLayout.createSequentialGroup()
                                .addComponent(jbBuscarUsuarioMod, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))))
                .addContainerGap())
        );
        jPanelModificarLayout.setVerticalGroup(
            jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificarLayout.createSequentialGroup()
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModificarLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jbBuscarUsuarioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfCedulaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtfNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtfApellidoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jbActualizarUsuarioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfContrasenaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jcbTipoUsuarioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarLayout.createSequentialGroup()
                        .addComponent(jbEliminarUsuarioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(jPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jbCancelarUsuarioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jbCerrarMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModificarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jTabbedPaneNuevoUsuario.addTab("Modificar Usuarios Existentes", jPanelModificar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneNuevoUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneNuevoUsuario)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarUsuarioModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarUsuarioModActionPerformed
        // TODO add your handling code here:
        BuscarUsuarioPorCedula();
    }//GEN-LAST:event_jbBuscarUsuarioModActionPerformed

    private void jbCancelarUsuarioModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarUsuarioModActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
        LimpiarCamposMod();
        BloquearControles();
        DesbloquearCostrolesIniciales();
        CargarTablaUsuarios("");
    }//GEN-LAST:event_jbCancelarUsuarioModActionPerformed

    private void jbCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearUsuarioActionPerformed
        // TODO add your handling code here:
        InsertarUsuario();
        CargarTablaUsuarios("");

    }//GEN-LAST:event_jbCrearUsuarioActionPerformed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        // TODO add your handling code here:
        CerrarVentana();
        LimpiarCamposMod();
        LimpiarCampos();

    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbCerrarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarModActionPerformed
        // TODO add your handling code here:
        CerrarVentana();
        CargarTablaUsuarios("");
    }//GEN-LAST:event_jbCerrarModActionPerformed

    private void jbActualizarUsuarioModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarUsuarioModActionPerformed
        // TODO add your handling code here:
        ActualizarUsuario();
        CargarTablaUsuarios("");
    }//GEN-LAST:event_jbActualizarUsuarioModActionPerformed

    private void jbEliminarUsuarioModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarUsuarioModActionPerformed
        // TODO add your handling code here:
        EliminarUsuario();
        CargarTablaUsuarios("");
    }//GEN-LAST:event_jbEliminarUsuarioModActionPerformed

    private void jtfCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCedulaActionPerformed

    private void jtfCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCedulaKeyTyped
        // TODO add your handling code here:
        int ced = 10;
        if (jtfCedula.getText().length() == ced) {
            evt.consume();
        }
        char caracter = evt.getKeyChar();

        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCedulaKeyTyped

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if (Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfCedulaModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCedulaModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCedulaModActionPerformed

    private void jtfCedulaModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCedulaModKeyTyped
        // TODO add your handling code here:
        int ced = 10;
        if (jtfCedulaMod.getText().length() == ced) {
            evt.consume();
        }
        char caracter = evt.getKeyChar();

        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCedulaModKeyTyped

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNombreMouseClicked
        // TODO add your handling code here:
        int ced = 10;
        if (jtfCedula.getText().length() < ced) {
            JOptionPane.showMessageDialog(this, "La Cédula Debe Tener 10 Dígitos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jtfCedula.requestFocus();
        }
    }//GEN-LAST:event_jtfNombreMouseClicked

    private void jtfNombreModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreModKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if (Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNombreModKeyTyped

    private void jtfApellidoModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoModKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if (Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfApellidoModKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCrear;
    private javax.swing.JPanel jPanelModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPaneNuevoUsuario;
    private javax.swing.JTable jTable_Usuarios;
    private javax.swing.JButton jbActualizarUsuarioMod;
    private javax.swing.JButton jbBuscarUsuarioMod;
    private javax.swing.JButton jbCancelarUsuarioMod;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbCerrarMod;
    private javax.swing.JButton jbCrearUsuario;
    private javax.swing.JButton jbEliminarUsuarioMod;
    private javax.swing.JComboBox<String> jcbTipoUsuario;
    private javax.swing.JComboBox<String> jcbTipoUsuarioMod;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfApellidoMod;
    private javax.swing.JTextField jtfCedula;
    private javax.swing.JTextField jtfCedulaMod;
    private javax.swing.JTextField jtfContrasena;
    private javax.swing.JTextField jtfContrasenaMod;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNombreMod;
    // End of variables declaration//GEN-END:variables

    private void CerrarVentana() {
        this.setVisible(false);
        LimpiarCamposMod();
        LimpiarCampos();
        BloquearControles();
        DesbloquearCostrolesIniciales();
    }

    private void BloquearControles() {
        jtfNombreMod.setEnabled(false);
        jtfApellidoMod.setEnabled(false);
        jtfContrasenaMod.setEnabled(false);
        jcbTipoUsuarioMod.setEnabled(false);
        jbActualizarUsuarioMod.setEnabled(false);
        jbEliminarUsuarioMod.setEnabled(false);
        jbCancelarUsuarioMod.setEnabled(false);
        jbCerrarMod.setEnabled(true);
    }

    private void BloquearControlesCuandoModifica() {
        jtfCedulaMod.setEnabled(false);
        jbCerrarMod.setEnabled(false);
    }

    private void DesbloquearControlesCuandoModifica() {
        jtfNombreMod.setEnabled(true);
        jtfApellidoMod.setEnabled(true);
        jtfContrasenaMod.setEnabled(true);
        jcbTipoUsuarioMod.setEnabled(true);
        jbActualizarUsuarioMod.setEnabled(true);
        jbEliminarUsuarioMod.setEnabled(true);
        jbCancelarUsuarioMod.setEnabled(true);
    }

    private void DesbloquearCostrolesIniciales() {
        jtfCedulaMod.setEnabled(true);
        jbBuscarUsuarioMod.setEnabled(true);
        jbCerrarMod.setEnabled(true);
    }

    private void LimpiarCamposMod() {
        jtfCedulaMod.setText("");
        jtfNombreMod.setText("");
        jtfApellidoMod.setText("");
        jtfContrasenaMod.setText("");
        jcbTipoUsuarioMod.setSelectedIndex(1);
    }

    private void LimpiarCampos() {
        jtfCedula.setText("");
        jtfNombre.setText("");
        jtfApellido.setText("");
        jtfContrasena.setText("");
        jcbTipoUsuario.setSelectedIndex(1);
    }

    public void CargarCBTipoUsuarios() {
        try {
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            String sqlIns = "select * from usuarios group by usu_perfil; ";
            java.sql.Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sqlIns);
            DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
            DefaultComboBoxModel dcbmMod = new DefaultComboBoxModel();
            jcbTipoUsuario.setModel(dcbm);
            jcbTipoUsuarioMod.setModel(dcbmMod);
            while (rs.next()) {
                jcbTipoUsuarioMod.addItem(rs.getString(5));
                jcbTipoUsuario.addItem(rs.getString(5));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, title, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void BuscarUsuarioPorCedula() {
        try {
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            String sqlIns = "SELECT * FROM USUARIOS WHERE USU_CEDULA='" + jtfCedulaMod.getText() + "';";
            java.sql.Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sqlIns);
            if (rs.next()) {
                jtfNombreMod.setText(rs.getString(2));
                jtfApellidoMod.setText(rs.getString(3));
                jtfContrasenaMod.setText(rs.getString(4));
                jcbTipoUsuarioMod.setSelectedItem(rs.getString(5));
                BloquearControlesCuandoModifica();
                DesbloquearControlesCuandoModifica();
            } else {
                JOptionPane.showMessageDialog(this, "¡ Usuario No Encontrado !", "Advertencia", 2);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, title, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void InsertarUsuario() {
        int ced = 10;

        if (jtfCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese El Nro. De Cédula", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jtfCedula.requestFocus();
        } else if (jtfCedula.getText().length() < ced) {
            JOptionPane.showMessageDialog(this, "La Cédula Debe Tener 10 Dígitos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jtfCedula.requestFocus();
        } else if (jtfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese El Nombre", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jtfNombre.requestFocus();
        } else if (jtfApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese El Apellido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jtfApellido.requestFocus();
        } else if (jtfContrasena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese La Contraseña", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jtfApellido.requestFocus();
        } else {
            try {

                String cedula = jtfCedula.getText();
                String nombre = jtfNombre.getText().toString().toUpperCase();
                String apellido = jtfApellido.getText().toString().toUpperCase();
                String contrasena = jtfContrasena.getText();
                String tipoPerfil = jcbTipoUsuario.getSelectedItem().toString();

                Conexion cc = new Conexion();
                Connection cn = cc.conectar();
                String sqlIns = "";
                sqlIns = "insert into usuarios values(?,?,?,?,?)";
                PreparedStatement psd = cn.prepareStatement(sqlIns);
                psd.setString(1, cedula);
                psd.setString(2, nombre);
                psd.setString(3, apellido);
                psd.setString(4, contrasena);
                psd.setString(5, tipoPerfil);

                psd.executeUpdate();
                LimpiarCamposMod();
                LimpiarCampos();
                JOptionPane.showMessageDialog(this, "¡ Registro De Usuario Agregado Exitosamente !");
                cn.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, title, JOptionPane.ERROR_MESSAGE);
            }
        }
    }


    public void CargarTablaUsuarios(String Dato) {
        try {
            String titulos[] = {"CÉDULAS DISPONIBLES"};
            String registros[] = new String[1];
            modelo = new DefaultTableModel(null, titulos);

            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            String sql = " ";
            sql = "select usu_cedula from usuarios where usu_cedula LIKE'%" + Dato + "%'order by usu_cedula"; //order by CED_EST desc //Para ordenar de forma descendente las cedulas 
            //EL % Sirve para buscar coincidencias dentro de la base de datos   
            //Para ordenar por apellido es "%'order by APE_EST"
            Statement psd = cn.createStatement(); //Permite manejar por celda la informacion 
            ResultSet rs = psd.executeQuery(sql); //Almacena Fila por fila en la variable rs
            while (rs.next()) {
                registros[0] = rs.getString("usu_cedula");

                modelo.addRow(registros);

            }

            jTable_Usuarios.setModel(modelo);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void ActualizarUsuario() {
        try {
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            String sqlUpd = "";
            sqlUpd = "UPDATE usuarios SET usu_nombre='" + jtfNombreMod.getText()
                    + "', usu_apellido='" + jtfApellidoMod.getText()
                    + "', usu_clave='" + jtfContrasenaMod.getText()
                    + "', usu_perfil='" + jcbTipoUsuarioMod.getSelectedItem().toString()
                    + "' WHERE usu_cedula='" + jtfCedulaMod.getText() + "';";
            PreparedStatement psd = cn.prepareStatement(sqlUpd);
            int n = psd.executeUpdate();
            if (n > 0) {
                LimpiarCamposMod();
                LimpiarCampos();
                BloquearControles();
                DesbloquearCostrolesIniciales();
                JOptionPane.showMessageDialog(this, "¡ Datos Actualizados Correctamente !", "Información", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, title, JOptionPane.ERROR_MESSAGE);
        }
    }

    public void EliminarUsuario() {
        try {
            if (JOptionPane.showConfirmDialog(this,
                    "¿Realmente Desea Eliminar Este Usuario?",
                    "Confirmar Eliminar Usuario",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == 0) {
                Conexion cc = new Conexion();
                Connection cn = cc.conectar();
                String sqlDel = "DELETE FROM usuarios WHERE usu_cedula='" + jtfCedulaMod.getText() + "';";
                PreparedStatement psd = cn.prepareStatement(sqlDel);
                int n = psd.executeUpdate();
                if (n > 0) {
                    LimpiarCamposMod();
                    LimpiarCampos();
                    BloquearControles();
                    DesbloquearCostrolesIniciales();
                    JOptionPane.showMessageDialog(this, "¡ Usuario Eliminado Exitosamente !", "Información", JOptionPane.INFORMATION_MESSAGE);

                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, title, JOptionPane.ERROR_MESSAGE);
        }
    }
}
